{
  "id": "54dbc16ca0f5c61398427b02",
  "date": "2015-02-12T17:25:27.1172014+00:00",
  "template_key": "event-error-summary",
  "data": {
    "Id": "54dbc16ca0f5c61398427b02",
    "Message": "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.",
    "Type": "NullReferenceException",
    "TypeFullName": "System.NullReferenceException",
    "Method": "AssociateWithCurrentThread",
    "MethodFullName": "System.Web.ThreadContext.AssociateWithCurrentThread"
  }
}